### PR TITLE
feature: add support for sh1106

### PR DESCRIPTION
**Pull request by hadifikri**
- Added support for `SH1106` OLED.
- Update the `i2c-bus` dependencies to `v.5.2.2`
- Add a few new APIs
  - `bluetooth` : draw a bluetooth icon
  - `battery`: draw an interactive battery indicator
  - `wifi`: draw an interactive WiFi signal indicator
  - `image`:  a wrapper for `drawRGBAImage` to draw a `PNG` files. support animation.
 
The code was restructured to accommodate multiple OLED drivers with a consistent API.

All of the APIs was tested for both drivers on 0.96 inch `SSD1306` and 1.3 inch `SH1106`  with 128x64 resolution using Raspberry Pi 4. The  `SH1106` however do not support the `scrolling` feature natively, thus was not implemented. Do consider using software i2c for `SH1106` in case of an error.

The package version is bumped to `v1.1.0`.

### CODE REVIEW

**Comment by lynniemagoo** [comment]
For this last commit about bonkers column addressing, why did you add the entire array  'coladdress'  only for the 128x64 display?  

From what I'm reading from your code and the datasheet, all the displays no matter whether 128x32, 128x64 or 96x16 all start with a low Column Address of 2.  

I can see in your code that for displays other than 128x64, you have low col start set to 0x02 and your OR this value with a 4 lsb of the col.  Same for the high col address where you right-shift by 4 to get the 4 msb.  

To me, it would seem that you'd be able to do something like this and achieve the same results without using the lookup table:
```
        // Ensure that column is only 0..127.
        col &= 0x7F;  
        // Column Bias is 2 for a SH1106 so add it to the column passed in.
        col += 0x02; // make this configurable if you like - you added coloffset but I don't see it being used anywhere

        var lowAddress = (col & 0x0F);
        var highAddress = 0x10 | (col >>> 4);
        var displaySeq = [
            this.PAGE_ADDR + page,
            lowAddress,
            highAddress
        ];
```

What am I missing?

This last commit you may not have intended to add to your PR but as you committed to master before PR was merged, it will be included.

Also, not sure if you've seen this project which was created to also support projects like this:

https://github.com/lynniemagoo/oled-font-pack

**Comment by hadifikri** [comment]
Thank you for the column addressing fix. Already applied it to the PR. I was limiting the tests to 128x64 since  both oleds that I have only support this resolution. Forgot to generalize it.

Thanks for the cool font library.

**Comment by lynniemagoo** [comment]
This is my opinion so please don't take offense. 

I don't recommend assigning the constant on line 70 to include the value of coloffset. On line 227 you used the magic value of of
0x02 instead of using coloffset member of the config object. 

You also left many commented lines in this PR and included my comments on the PR comments. 

These will only serve to confuse people.  I would recommend removing all the unnecessary stuff you left in sh1106.js.

**Comment by hadifikri** [comment]
No problem. I've cleaned up the code accordingly.  I'll appreciate any comment.

**Comment by lynniemagoo** [comment]
**You messed up package.json - See the double-hyphen below that you added.**

  "name": "oled--i2c-bus",
  "version": "1.1.0",

I see you now have like 14 commits for all your changes.  This becomes very difficult to read/follow.


Here's what I would suggest.  You currently have a  local copy of your git repository.  

1) Remove the upstream remote from your repository.  **git remote remove origin**
2) Squash all your commits.  See https://www.git-tower.com/learn/git/faq/git-squash or Answer here using TortoiseGit.  https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

Note that there are multiple ways to Squash commits.  One is to do a merge and ask for all things to be squashed.  This would mean you'd need to have a pre-change branch already in your local repo which I doubt you do as you are working on master.

3) Delete your fork of this project in Github.

4) Fork this project again so you have a fully clean copy.

5) Reconnect your remote using **git remote add origin [url of your new fork]**

6) After squashing all your commits you have clean git history and can do a push to your new origin.  

7) Now, you can create a  PR into this project with a single commit that shows everything you touched without having to sort through all this chatter.  

Note that if you chose this path, delete/close this PR and then open another citing the feature issue, which by the way you closed way too early.

**Pull request closed without merging**
